server:
  port: 8087
kafka:
  topic:
    name: yanki-request
spring:
  application:
    name: yanki-mobile
  data:
    mongodb:
      uri: mongodb+srv://lucio2022:lucio123@bootcamp-may.ucmqo.mongodb.net/Bootcamp-May?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${COMPUTERNAME:localhost}